<?php

/**
 * This is the model base class for the table "tbl_opera_opera_genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OperaOperaGenre".
 *
 * Columns in table "tbl_opera_opera_genre" available as properties of the model,
 * followed by relations of table "tbl_opera_opera_genre" available as properties of the model.
 *
 * @property string $id
 * @property string $opera
 * @property string $opera_genre
 *
 * @property Opera $opera0
 * @property OperaGenre $operaGenre
 */
abstract class BaseOperaOperaGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_opera_opera_genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OperaOperaGenre|OperaOperaGenres', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('opera, opera_genre', 'required'),
			array('opera, opera_genre', 'length', 'max'=>20),
			array('id, opera, opera_genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'opera0' => array(self::BELONGS_TO, 'Opera', 'opera'),
			'operaGenre' => array(self::BELONGS_TO, 'OperaGenre', 'opera_genre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'opera' => null,
			'opera_genre' => null,
			'opera0' => null,
			'operaGenre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('opera', $this->opera);
		$criteria->compare('opera_genre', $this->opera_genre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}