<?php

/**
 * This is the model base class for the table "tbl_person_place_of_birth".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonPlaceOfBirth".
 *
 * Columns in table "tbl_person_place_of_birth" available as properties of the model,
 * followed by relations of table "tbl_person_place_of_birth" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $place_of_birth
 *
 * @property Person $person0
 * @property Location $placeOfBirth
 */
abstract class BasePersonPlaceOfBirth extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_place_of_birth';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonPlaceOfBirth|PersonPlaceOfBirths', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, place_of_birth', 'required'),
			array('person, place_of_birth', 'length', 'max'=>20),
			array('id, person, place_of_birth', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'placeOfBirth' => array(self::BELONGS_TO, 'Location', 'place_of_birth'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'place_of_birth' => null,
			'person0' => null,
			'placeOfBirth' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('place_of_birth', $this->place_of_birth);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}