<?php

/**
 * This is the model base class for the table "tbl_play_play_genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlayPlayGenre".
 *
 * Columns in table "tbl_play_play_genre" available as properties of the model,
 * followed by relations of table "tbl_play_play_genre" available as properties of the model.
 *
 * @property string $id
 * @property string $play
 * @property string $play_genre
 *
 * @property Play $play0
 * @property PlayGenre $playGenre
 */
abstract class BasePlayPlayGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_play_play_genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlayPlayGenre|PlayPlayGenres', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('play, play_genre', 'required'),
			array('play, play_genre', 'length', 'max'=>20),
			array('id, play, play_genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'play0' => array(self::BELONGS_TO, 'Play', 'play'),
			'playGenre' => array(self::BELONGS_TO, 'PlayGenre', 'play_genre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'play' => null,
			'play_genre' => null,
			'play0' => null,
			'playGenre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('play', $this->play);
		$criteria->compare('play_genre', $this->play_genre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}