<?php

/**
 * This is the model base class for the table "tbl_person".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Person".
 *
 * Columns in table "tbl_person" available as properties of the model,
 * followed by relations of table "tbl_person" available as properties of the model.
 *
 * @property string $id
 * @property string $wikiid
 * @property string $guid
 * @property string $fbid
 * @property string $name
 * @property string $description
 *
 * @property PersonChildren[] $personChildrens
 * @property PersonChildren[] $personChildrens1
 * @property PersonEducation[] $personEducations
 * @property PersonEmployment[] $personEmployments
 * @property PersonEthnicity[] $personEthnicities
 * @property PersonGender[] $personGenders
 * @property PersonNationality[] $personNationalities
 * @property PersonParent[] $personParents
 * @property PersonParent[] $personParents1
 * @property PersonPlaceOfBirth[] $personPlaceOfBirths
 * @property PersonPlacesLived[] $personPlacesLiveds
 * @property PersonProfession[] $personProfessions
 * @property PersonQuotation[] $personQuotations
 * @property PersonReligion[] $personReligions
 * @property PersonSibling[] $personSiblings
 * @property PersonSibling[] $personSiblings1
 * @property PersonSpouse[] $personSpouses
 * @property PersonSpouse[] $personSpouses1
 */
abstract class BasePerson extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Person|people', $n);
	}

	public static function representingColumn() {
		return 'wikiid';
	}

	public function rules() {
		return array(
			array('wikiid', 'length', 'max'=>127),
			array('guid, fbid', 'length', 'max'=>63),
			array('name, description', 'safe'),
			array('wikiid, guid, fbid, name, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, wikiid, guid, fbid, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'personChildrens' => array(self::HAS_MANY, 'PersonChildren', 'person'),
			'personChildrens1' => array(self::HAS_MANY, 'PersonChildren', 'children'),
			'personEducations' => array(self::HAS_MANY, 'PersonEducation', 'person'),
			'personEmployments' => array(self::HAS_MANY, 'PersonEmployment', 'person'),
			'personEthnicities' => array(self::HAS_MANY, 'PersonEthnicity', 'person'),
			'personGenders' => array(self::HAS_MANY, 'PersonGender', 'person'),
			'personNationalities' => array(self::HAS_MANY, 'PersonNationality', 'person'),
			'personParents' => array(self::HAS_MANY, 'PersonParent', 'person'),
			'personParents1' => array(self::HAS_MANY, 'PersonParent', 'parentt'),
			'personPlaceOfBirths' => array(self::HAS_MANY, 'PersonPlaceOfBirth', 'person'),
			'personPlacesLiveds' => array(self::HAS_MANY, 'PersonPlacesLived', 'person'),
			'personProfessions' => array(self::HAS_MANY, 'PersonProfession', 'person'),
			'personQuotations' => array(self::HAS_MANY, 'PersonQuotation', 'person'),
			'personReligions' => array(self::HAS_MANY, 'PersonReligion', 'person'),
			'personSiblings' => array(self::HAS_MANY, 'PersonSibling', 'person'),
			'personSiblings1' => array(self::HAS_MANY, 'PersonSibling', 'sibling'),
			'personSpouses' => array(self::HAS_MANY, 'PersonSpouse', 'person'),
			'personSpouses1' => array(self::HAS_MANY, 'PersonSpouse', 'spouse'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'wikiid' => Yii::t('app', 'Wikiid'),
			'guid' => Yii::t('app', 'Guid'),
			'fbid' => Yii::t('app', 'Fbid'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'personChildrens' => null,
			'personChildrens1' => null,
			'personEducations' => null,
			'personEmployments' => null,
			'personEthnicities' => null,
			'personGenders' => null,
			'personNationalities' => null,
			'personParents' => null,
			'personParents1' => null,
			'personPlaceOfBirths' => null,
			'personPlacesLiveds' => null,
			'personProfessions' => null,
			'personQuotations' => null,
			'personReligions' => null,
			'personSiblings' => null,
			'personSiblings1' => null,
			'personSpouses' => null,
			'personSpouses1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('wikiid', $this->wikiid, true);
		$criteria->compare('guid', $this->guid, true);
		$criteria->compare('fbid', $this->fbid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}