<?php

/**
 * This is the model base class for the table "tbl_tv_program_language".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgramLanguage".
 *
 * Columns in table "tbl_tv_program_language" available as properties of the model,
 * followed by relations of table "tbl_tv_program_language" available as properties of the model.
 *
 * @property string $id
 * @property string $tv_program
 * @property string $language
 *
 * @property TvProgram $tvProgram
 * @property Language $language0
 */
abstract class BaseTvProgramLanguage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_program_language';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgramLanguage|TvProgramLanguages', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('tv_program, language', 'required'),
			array('tv_program, language', 'length', 'max'=>20),
			array('id, tv_program, language', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tvProgram' => array(self::BELONGS_TO, 'TvProgram', 'tv_program'),
			'language0' => array(self::BELONGS_TO, 'Language', 'language'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tv_program' => null,
			'language' => null,
			'tvProgram' => null,
			'language0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('tv_program', $this->tv_program);
		$criteria->compare('language', $this->language);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}