<?php

/**
 * This is the model base class for the table "tbl_person_religion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonReligion".
 *
 * Columns in table "tbl_person_religion" available as properties of the model,
 * followed by relations of table "tbl_person_religion" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $religion
 *
 * @property Person $person0
 * @property Religion $religion0
 */
abstract class BasePersonReligion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_religion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonReligion|PersonReligions', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, religion', 'required'),
			array('person, religion', 'length', 'max'=>20),
			array('id, person, religion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'religion0' => array(self::BELONGS_TO, 'Religion', 'religion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'religion' => null,
			'person0' => null,
			'religion0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('religion', $this->religion);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}