<?php

/**
 * This is the model base class for the table "tbl_tv_program_tv_theme_song".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgramTvThemeSong".
 *
 * Columns in table "tbl_tv_program_tv_theme_song" available as properties of the model,
 * followed by relations of table "tbl_tv_program_tv_theme_song" available as properties of the model.
 *
 * @property string $id
 * @property string $tv_program
 * @property string $tv_theme_song
 *
 * @property TvProgram $tvProgram
 * @property TvThemeSong $tvThemeSong
 */
abstract class BaseTvProgramTvThemeSong extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_program_tv_theme_song';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgramTvThemeSong|TvProgramTvThemeSongs', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('tv_program, tv_theme_song', 'required'),
			array('tv_program, tv_theme_song', 'length', 'max'=>20),
			array('id, tv_program, tv_theme_song', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tvProgram' => array(self::BELONGS_TO, 'TvProgram', 'tv_program'),
			'tvThemeSong' => array(self::BELONGS_TO, 'TvThemeSong', 'tv_theme_song'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tv_program' => null,
			'tv_theme_song' => null,
			'tvProgram' => null,
			'tvThemeSong' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('tv_program', $this->tv_program);
		$criteria->compare('tv_theme_song', $this->tv_theme_song);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}