<?php

/**
 * This is the model base class for the table "tbl_book_character".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BookCharacter".
 *
 * Columns in table "tbl_book_character" available as properties of the model,
 * followed by relations of table "tbl_book_character" available as properties of the model.
 *
 * @property string $id
 * @property string $book
 * @property string $character_
 *
 * @property Book $book0
 * @property Character $character
 */
abstract class BaseBookCharacter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_book_character';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BookCharacter|BookCharacters', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('book, character_', 'required'),
			array('book, character_', 'length', 'max'=>20),
			array('id, book, character_', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'book0' => array(self::BELONGS_TO, 'Book', 'book'),
			'character' => array(self::BELONGS_TO, 'Character', 'character_'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'book' => null,
			'character_' => null,
			'book0' => null,
			'character' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('book', $this->book);
		$criteria->compare('character_', $this->character_);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}