<?php

/**
 * This is the model base class for the table "tbl_game_game_genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GameGameGenre".
 *
 * Columns in table "tbl_game_game_genre" available as properties of the model,
 * followed by relations of table "tbl_game_game_genre" available as properties of the model.
 *
 * @property string $id
 * @property string $game
 * @property string $genre
 *
 * @property GameGenre $genre0
 * @property Game $game0
 */
abstract class BaseGameGameGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_game_game_genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GameGameGenre|GameGameGenres', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('game, genre', 'required'),
			array('game, genre', 'length', 'max'=>20),
			array('id, game, genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'genre0' => array(self::BELONGS_TO, 'GameGenre', 'genre'),
			'game0' => array(self::BELONGS_TO, 'Game', 'game'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'game' => null,
			'genre' => null,
			'genre0' => null,
			'game0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('game', $this->game);
		$criteria->compare('genre', $this->genre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}