<?php

/**
 * This is the model base class for the table "tbl_person_sibling".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonSibling".
 *
 * Columns in table "tbl_person_sibling" available as properties of the model,
 * followed by relations of table "tbl_person_sibling" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $sibling
 *
 * @property Person $person0
 * @property Person $sibling0
 */
abstract class BasePersonSibling extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_sibling';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonSibling|PersonSiblings', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, sibling', 'required'),
			array('person, sibling', 'length', 'max'=>20),
			array('id, person, sibling', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'sibling0' => array(self::BELONGS_TO, 'Person', 'sibling'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'sibling' => null,
			'person0' => null,
			'sibling0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('sibling', $this->sibling);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}