<?php

/**
 * This is the model base class for the table "tbl_person_parent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonParent".
 *
 * Columns in table "tbl_person_parent" available as properties of the model,
 * followed by relations of table "tbl_person_parent" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $parentt
 *
 * @property Person $person0
 * @property Person $parentt0
 */
abstract class BasePersonParent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_parent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonParent|PersonParents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, parentt', 'required'),
			array('person, parentt', 'length', 'max'=>20),
			array('id, person, parentt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'parentt0' => array(self::BELONGS_TO, 'Person', 'parentt'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'parentt' => null,
			'person0' => null,
			'parentt0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('parentt', $this->parentt);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}