<?php

/**
 * This is the model base class for the table "tbl_book_subject".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BookSubject".
 *
 * Columns in table "tbl_book_subject" available as properties of the model,
 * followed by relations of table "tbl_book_subject" available as properties of the model.
 *
 * @property string $id
 * @property string $book
 * @property string $subject
 *
 * @property Book $book0
 * @property Subject $subject0
 */
abstract class BaseBookSubject extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_book_subject';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BookSubject|BookSubjects', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('book, subject', 'required'),
			array('book, subject', 'length', 'max'=>20),
			array('id, book, subject', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'book0' => array(self::BELONGS_TO, 'Book', 'book'),
			'subject0' => array(self::BELONGS_TO, 'Subject', 'subject'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'book' => null,
			'subject' => null,
			'book0' => null,
			'subject0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('book', $this->book);
		$criteria->compare('subject', $this->subject);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}