<?php

/**
 * This is the model base class for the table "tbl_person_employment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonEmployment".
 *
 * Columns in table "tbl_person_employment" available as properties of the model,
 * followed by relations of table "tbl_person_employment" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $employment
 *
 * @property Employment $employment0
 * @property Person $person0
 */
abstract class BasePersonEmployment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_employment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonEmployment|PersonEmployments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, employment', 'required'),
			array('person, employment', 'length', 'max'=>20),
			array('id, person, employment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employment0' => array(self::BELONGS_TO, 'Employment', 'employment'),
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'employment' => null,
			'employment0' => null,
			'person0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('employment', $this->employment);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}