<?php

/**
 * This is the model base class for the table "tbl_person_quotation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonQuotation".
 *
 * Columns in table "tbl_person_quotation" available as properties of the model,
 * followed by relations of table "tbl_person_quotation" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $quotation
 *
 * @property Person $person0
 * @property Quotation $quotation0
 */
abstract class BasePersonQuotation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_quotation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonQuotation|PersonQuotations', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, quotation', 'required'),
			array('person, quotation', 'length', 'max'=>20),
			array('id, person, quotation', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'quotation0' => array(self::BELONGS_TO, 'Quotation', 'quotation'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'quotation' => null,
			'person0' => null,
			'quotation0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('quotation', $this->quotation);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}