<?php

/**
 * This is the model base class for the table "tbl_statement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Statement".
 *
 * Columns in table "tbl_statement" available as properties of the model,
 * followed by relations of table "tbl_statement" available as properties of the model.
 *
 * @property string $id
 * @property string $attribute
 * @property string $value
 * @property string $query
 *
 * @property Query $query0
 */
abstract class BaseStatement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_statement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Statement|Statements', $n);
	}

	public static function representingColumn() {
		return 'attribute';
	}

	public function rules() {
		return array(
			array('attribute, value, query', 'required'),
			array('attribute, value', 'length', 'max'=>127),
			array('query', 'length', 'max'=>20),
			array('id, attribute, value, query', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'query0' => array(self::BELONGS_TO, 'Query', 'query'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'attribute' => Yii::t('app', 'Attribute'),
			'value' => Yii::t('app', 'Value'),
			'query' => null,
			'query0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('attribute', $this->attribute, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('query', $this->query);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}