<?php

/**
 * This is the model base class for the table "tbl_tv_program_tv_producer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgramTvProducer".
 *
 * Columns in table "tbl_tv_program_tv_producer" available as properties of the model,
 * followed by relations of table "tbl_tv_program_tv_producer" available as properties of the model.
 *
 * @property string $id
 * @property string $tv_program
 * @property string $tv_producer
 *
 * @property TvProgram $tvProgram
 * @property TvProducer $tvProducer
 */
abstract class BaseTvProgramTvProducer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_program_tv_producer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgramTvProducer|TvProgramTvProducers', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('tv_program, tv_producer', 'required'),
			array('tv_program, tv_producer', 'length', 'max'=>20),
			array('id, tv_program, tv_producer', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tvProgram' => array(self::BELONGS_TO, 'TvProgram', 'tv_program'),
			'tvProducer' => array(self::BELONGS_TO, 'TvProducer', 'tv_producer'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tv_program' => null,
			'tv_producer' => null,
			'tvProgram' => null,
			'tvProducer' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('tv_program', $this->tv_program);
		$criteria->compare('tv_producer', $this->tv_producer);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}