<?php

/**
 * This is the model base class for the table "tbl_person_places_lived".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonPlacesLived".
 *
 * Columns in table "tbl_person_places_lived" available as properties of the model,
 * followed by relations of table "tbl_person_places_lived" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $places_lived
 *
 * @property Person $person0
 * @property Location $placesLived
 */
abstract class BasePersonPlacesLived extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_places_lived';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonPlacesLived|PersonPlacesLiveds', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, places_lived', 'required'),
			array('person, places_lived', 'length', 'max'=>20),
			array('id, person, places_lived', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'placesLived' => array(self::BELONGS_TO, 'Location', 'places_lived'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'places_lived' => null,
			'person0' => null,
			'placesLived' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('places_lived', $this->places_lived);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}