<?php

/**
 * This is the model base class for the table "tbl_person_education".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonEducation".
 *
 * Columns in table "tbl_person_education" available as properties of the model,
 * followed by relations of table "tbl_person_education" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $education
 *
 * @property Person $person0
 * @property Education $education0
 */
abstract class BasePersonEducation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_education';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonEducation|PersonEducations', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, education', 'required'),
			array('person, education', 'length', 'max'=>20),
			array('id, person, education', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'education0' => array(self::BELONGS_TO, 'Education', 'education'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'education' => null,
			'person0' => null,
			'education0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('education', $this->education);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}