<?php

/**
 * This is the model base class for the table "tbl_tv_program_only".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgramOnly".
 *
 * Columns in table "tbl_tv_program_only" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $wikiid
 * @property string $guid
 * @property string $fbid
 * @property string $name
 * @property string $description
 * @property string $air_date_of_first_episode
 * @property string $air_date_of_final_episode
 * @property string $number_of_seasons
 * @property string $number_of_episodes
 * @property string $episode_running_time
 * @property string $thetvdb_id
 * @property string $tvrage_id
 * @property string $hulu_id
 * @property string $tvguide_id
 * @property string $currently_in_production
 * @property string $notable_type
 *
 */
abstract class BaseTvProgramOnly extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_program_only';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgramOnly|TvProgramOnlies', $n);
	}

	public static function representingColumn() {
		return 'wikiid';
	}

	public function rules() {
		return array(
			array('id', 'length', 'max'=>20),
			array('wikiid', 'length', 'max'=>127),
			array('guid, fbid, air_date_of_first_episode, air_date_of_final_episode, number_of_seasons, number_of_episodes, episode_running_time, thetvdb_id, tvrage_id, hulu_id, tvguide_id, currently_in_production', 'length', 'max'=>63),
			array('notable_type', 'length', 'max'=>255),
			array('name, description', 'safe'),
			array('id, wikiid, guid, fbid, name, description, air_date_of_first_episode, air_date_of_final_episode, number_of_seasons, number_of_episodes, episode_running_time, thetvdb_id, tvrage_id, hulu_id, tvguide_id, currently_in_production, notable_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, wikiid, guid, fbid, name, description, air_date_of_first_episode, air_date_of_final_episode, number_of_seasons, number_of_episodes, episode_running_time, thetvdb_id, tvrage_id, hulu_id, tvguide_id, currently_in_production, notable_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'wikiid' => Yii::t('app', 'Wikiid'),
			'guid' => Yii::t('app', 'Guid'),
			'fbid' => Yii::t('app', 'Fbid'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'air_date_of_first_episode' => Yii::t('app', 'Air Date Of First Episode'),
			'air_date_of_final_episode' => Yii::t('app', 'Air Date Of Final Episode'),
			'number_of_seasons' => Yii::t('app', 'Number Of Seasons'),
			'number_of_episodes' => Yii::t('app', 'Number Of Episodes'),
			'episode_running_time' => Yii::t('app', 'Episode Running Time'),
			'thetvdb_id' => Yii::t('app', 'Thetvdb'),
			'tvrage_id' => Yii::t('app', 'Tvrage'),
			'hulu_id' => Yii::t('app', 'Hulu'),
			'tvguide_id' => Yii::t('app', 'Tvguide'),
			'currently_in_production' => Yii::t('app', 'Currently In Production'),
			'notable_type' => Yii::t('app', 'Notable Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('wikiid', $this->wikiid, true);
		$criteria->compare('guid', $this->guid, true);
		$criteria->compare('fbid', $this->fbid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('air_date_of_first_episode', $this->air_date_of_first_episode, true);
		$criteria->compare('air_date_of_final_episode', $this->air_date_of_final_episode, true);
		$criteria->compare('number_of_seasons', $this->number_of_seasons, true);
		$criteria->compare('number_of_episodes', $this->number_of_episodes, true);
		$criteria->compare('episode_running_time', $this->episode_running_time, true);
		$criteria->compare('thetvdb_id', $this->thetvdb_id, true);
		$criteria->compare('tvrage_id', $this->tvrage_id, true);
		$criteria->compare('hulu_id', $this->hulu_id, true);
		$criteria->compare('tvguide_id', $this->tvguide_id, true);
		$criteria->compare('currently_in_production', $this->currently_in_production, true);
		$criteria->compare('notable_type', $this->notable_type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}