<?php

/**
 * This is the model base class for the table "tbl_person_education_distinct".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonEducationDistinct".
 *
 * Columns in table "tbl_person_education_distinct" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $person
 * @property string $education
 *
 */
abstract class BasePersonEducationDistinct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_education_distinct';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonEducationDistinct|PersonEducationDistincts', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person', 'required'),
			array('id, person, education', 'length', 'max'=>20),
			array('id, education', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, person, education', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => Yii::t('app', 'Person'),
			'education' => Yii::t('app', 'Education'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person, true);
		$criteria->compare('education', $this->education, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}