<?php

/**
 * This is the model base class for the table "tbl_person_ethnicity".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonEthnicity".
 *
 * Columns in table "tbl_person_ethnicity" available as properties of the model,
 * followed by relations of table "tbl_person_ethnicity" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $ethnicity
 *
 * @property Person $person0
 * @property Ethnicity $ethnicity0
 */
abstract class BasePersonEthnicity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_ethnicity';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonEthnicity|PersonEthnicities', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, ethnicity', 'required'),
			array('person, ethnicity', 'length', 'max'=>20),
			array('id, person, ethnicity', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'ethnicity0' => array(self::BELONGS_TO, 'Ethnicity', 'ethnicity'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'ethnicity' => null,
			'person0' => null,
			'ethnicity0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('ethnicity', $this->ethnicity);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}