<?php

/**
 * This is the model base class for the table "tbl_tv_program_and_film_w_notable_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgramAndFilmWNotableType".
 *
 * Columns in table "tbl_tv_program_and_film_w_notable_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $fbid
 * @property string $name
 * @property string $description
 * @property string $notable_type
 *
 */
abstract class BaseTvProgramAndFilmWNotableType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_program_and_film_w_notable_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgramAndFilmWNotableType|TvProgramAndFilmWNotableTypes', $n);
	}

	public static function representingColumn() {
		return 'fbid';
	}

	public function rules() {
		return array(
			array('id', 'length', 'max'=>20),
			array('fbid', 'length', 'max'=>63),
			array('notable_type', 'length', 'max'=>255),
			array('name, description', 'safe'),
			array('id, fbid, name, description, notable_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fbid, name, description, notable_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fbid' => Yii::t('app', 'Fbid'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'notable_type' => Yii::t('app', 'Notable Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('fbid', $this->fbid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('notable_type', $this->notable_type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}