<?php

/**
 * This is the model base class for the table "tbl_person_nationality".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonNationality".
 *
 * Columns in table "tbl_person_nationality" available as properties of the model,
 * followed by relations of table "tbl_person_nationality" available as properties of the model.
 *
 * @property string $id
 * @property string $person
 * @property string $nationality
 *
 * @property Person $person0
 * @property Nationality $nationality0
 */
abstract class BasePersonNationality extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_person_nationality';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonNationality|PersonNationalities', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person, nationality', 'required'),
			array('person, nationality', 'length', 'max'=>20),
			array('id, person, nationality', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person0' => array(self::BELONGS_TO, 'Person', 'person'),
			'nationality0' => array(self::BELONGS_TO, 'Nationality', 'nationality'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person' => null,
			'nationality' => null,
			'person0' => null,
			'nationality0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('person', $this->person);
		$criteria->compare('nationality', $this->nationality);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}