<?php

/**
 * This is the model base class for the table "tbl_nationality_continent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NationalityContinent".
 *
 * Columns in table "tbl_nationality_continent" available as properties of the model,
 * followed by relations of table "tbl_nationality_continent" available as properties of the model.
 *
 * @property string $id
 * @property string $nationality
 * @property string $continent
 *
 * @property Continent $continent0
 * @property Nationality $nationality0
 */
abstract class BaseNationalityContinent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_nationality_continent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NationalityContinent|NationalityContinents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('nationality, continent', 'required'),
			array('nationality, continent', 'length', 'max'=>20),
			array('id, nationality, continent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'continent0' => array(self::BELONGS_TO, 'Continent', 'continent'),
			'nationality0' => array(self::BELONGS_TO, 'Nationality', 'nationality'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nationality' => null,
			'continent' => null,
			'continent0' => null,
			'nationality0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('nationality', $this->nationality);
		$criteria->compare('continent', $this->continent);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}