<?php

/**
 * This is the model base class for the table "tbl_tv_prog_genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TvProgGenre".
 *
 * Columns in table "tbl_tv_prog_genre" available as properties of the model,
 * followed by relations of table "tbl_tv_prog_genre" available as properties of the model.
 *
 * @property string $id
 * @property string $tv
 * @property string $prog_genre
 *
 * @property Tv $tv0
 * @property ProgGenre $progGenre
 */
abstract class BaseTvProgGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tv_prog_genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TvProgGenre|TvProgGenres', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('tv, prog_genre', 'required'),
			array('tv, prog_genre', 'length', 'max'=>20),
			array('id, tv, prog_genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tv0' => array(self::BELONGS_TO, 'Tv', 'tv'),
			'progGenre' => array(self::BELONGS_TO, 'ProgGenre', 'prog_genre'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tv' => null,
			'prog_genre' => null,
			'tv0' => null,
			'progGenre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('tv', $this->tv);
		$criteria->compare('prog_genre', $this->prog_genre);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}